### PR TITLE
Configure LSP semantic highlights added in nvim .9.0

### PR DESCRIPTION
**Pull request by svrana**

### CODE REVIEW

**Comment by svrana** [comment]
Still needs more testing.

**Comment by jabuxas** [comment]
can't add it manually to my config, errors out with

```
stack traceback:
^I.../share/nvim/lazy/colorbuddy.vim/lua/colorbuddy/group.lua:182: in function 'handle_group_argument'
^I.../share/nvim/lazy/colorbuddy.vim/lua/colorbuddy/group.lua:196: in function 'link'
^I/home/jab/.config/nvim/lua/custom/plugins/neosolarized.lua:39: in function 'config'
^I...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:348: in function <...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:346>
^I[C]: in function 'xpcall'
^I.../.local/share/nvim/lazy/lazy.nvim/lua/lazy/core/util.lua:110: in function 'try'
^I...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:363: in function 'config'
^I...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:330: in function '_load'
^I...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:184: in function 'load'
^I...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:116: in function 'startup'
^I...e/jab/.local/share/nvim/lazy/lazy.nvim/lua/lazy/init.lua:85: in function 'setup'
^I/home/jab/.config/nvim/init.lua:19: in main chunk
```
is it something on my end?

**Comment by svrana** [comment]
Thanks for looking at this. Can you try again now? There were some problems... Not sure how I could have tested this before given the problems, so I'll stay on this branch for a while. Thanks @jabuxas!

**Comment by jabuxas** [comment]
seems to be back to normal behaviour :+1: . with the pull request content added to my config looks normal:
image



without it
image

**Comment by svrana** [comment]
Ok, you've convinced me.. The first screenshot is clearly better. ;) Merging.

**Pull request merged**
